export enum Key {
  Number0 = "0",
  Number1 = "1",
  Number2 = "2",
  Number3 = "3",
  Number4 = "4",
  Number5 = "5",
  Number6 = "6",
  Number7 = "7",
  Number8 = "8",
  Number9 = "9",
  Delete = "Delete",
  Confirm = "Confirm",
  Back = "Back",
  Submit = "Submit",
}
