name: web

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: install
        run: bun i
      - name: build
        run: cd web && bun run build
      - name: configure
        uses: actions/configure-pages@v3
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: web/dist
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v2
      - name: 'logging'
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"
